/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeasureRouteImport } from './routes/measure'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBillsPerfectRouteImport } from './routes/api/bills.perfect'
import { Route as ApiBillsImperfectRouteImport } from './routes/api/bills.imperfect'

const MeasureRoute = MeasureRouteImport.update({
  id: '/measure',
  path: '/measure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillsPerfectRoute = ApiBillsPerfectRouteImport.update({
  id: '/api/bills/perfect',
  path: '/api/bills/perfect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillsImperfectRoute = ApiBillsImperfectRouteImport.update({
  id: '/api/bills/imperfect',
  path: '/api/bills/imperfect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/measure': typeof MeasureRoute
  '/api/bills/imperfect': typeof ApiBillsImperfectRoute
  '/api/bills/perfect': typeof ApiBillsPerfectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/measure': typeof MeasureRoute
  '/api/bills/imperfect': typeof ApiBillsImperfectRoute
  '/api/bills/perfect': typeof ApiBillsPerfectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/measure': typeof MeasureRoute
  '/api/bills/imperfect': typeof ApiBillsImperfectRoute
  '/api/bills/perfect': typeof ApiBillsPerfectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/measure' | '/api/bills/imperfect' | '/api/bills/perfect'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/measure' | '/api/bills/imperfect' | '/api/bills/perfect'
  id:
    | '__root__'
    | '/'
    | '/measure'
    | '/api/bills/imperfect'
    | '/api/bills/perfect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeasureRoute: typeof MeasureRoute
  ApiBillsImperfectRoute: typeof ApiBillsImperfectRoute
  ApiBillsPerfectRoute: typeof ApiBillsPerfectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/measure': {
      id: '/measure'
      path: '/measure'
      fullPath: '/measure'
      preLoaderRoute: typeof MeasureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bills/perfect': {
      id: '/api/bills/perfect'
      path: '/api/bills/perfect'
      fullPath: '/api/bills/perfect'
      preLoaderRoute: typeof ApiBillsPerfectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bills/imperfect': {
      id: '/api/bills/imperfect'
      path: '/api/bills/imperfect'
      fullPath: '/api/bills/imperfect'
      preLoaderRoute: typeof ApiBillsImperfectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeasureRoute: MeasureRoute,
  ApiBillsImperfectRoute: ApiBillsImperfectRoute,
  ApiBillsPerfectRoute: ApiBillsPerfectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
